import fs from 'node:fs';
import * as cheerio from 'cheerio';
const $ = cheerio.load(fs.readFileSync('index.html', 'utf8'));
$('.brand').html('<img src="/assets/metal-rack-logo.png" alt="Metall Rack" width="240" height="80">');
$('.topline .container').html('<span>MR — INFRAESTRUTURA EM METAL</span><span>DATA CENTER / TELECOM / ENERGIA</span>');
$('.hero-copy .eyebrow').html('<span></span> ESTRUTURAS PARA OPERAÇÕES EXIGENTES');
$('.hero h1').html('METAL.<br>ESTRUTURA.<br><em>CONEXÃO.</em>');
$('.hero .intro').text('O que sustenta a sua rede importa. Racks, gabinetes e acessórios para organizar e proteger cada conexão.');
$('.hero-copy>.button').html('ENCONTRE SEU RACK <span>↗</span>');
$('.hero-note').html('<span class="technical-cross" aria-hidden="true">+</span><p>PADRÃO 19” · PROJETOS SOB MEDIDA<br><strong>Da estrutura ao último ponto de conexão.</strong></p>');
$('.hero-visual').prepend('<span class="hero-backtype" aria-hidden="true">MR</span><span class="measure" aria-hidden="true">ESTRUTURA / PROTEÇÃO / ORGANIZAÇÃO</span>');
$('.visual-label').text('SÉRIE / DATA CENTER');
$('.vertical-label').text('RACK SERVER — VISTA EM PERSPECTIVA');
$('.visual-index').text('MR—02');
$('.hero').wrap('<div class="hero-shell"></div>');
$('.applications .container').html('<span>FEITO PARA<br><strong>SUSTENTAR.</strong></span><a href="#produtos" data-line="rack"><small>01 / INFRAESTRUTURA</small>DATA CENTER <span>↗</span></a><a href="#produtos" data-line="rack"><small>02 / CONECTIVIDADE</small>TELECOM <span>↗</span></a><a href="#produtos" data-line="energia"><small>03 / PROTEÇÃO</small>ENERGIA <span>↗</span></a><a href="#produtos" data-line="fibra"><small>04 / TRANSMISSÃO</small>FIBRA ÓPTICA <span>↗</span></a>');
$('.section-heading .eyebrow').text('01 — CATÁLOGO DE PRODUTOS');
$('.section-heading h2').html('A BASE DA<br>SUA OPERAÇÃO.');
$('.section-heading>p').html('Da infraestrutura ao detalhe.<br>Explore nossas linhas de produtos.');
$('.catalog-tools,.result-count,.product-grid,.empty').wrapAll('<div class="catalog-layout"></div>');
$('.catalog-tools').prepend('<p class="filter-label">ENCONTRE SUA SOLUÇÃO</p>');
$('.about .eyebrow').text('02 — METALL RACK');
$('.about h2').html('A FORÇA ESTÁ<br>NA <em>ESTRUTURA.</em>');
$('.about-grid').prepend('<div class="about-mark" aria-hidden="true">19<span>”</span><small>DA CONEXÃO À ESTRUTURA.</small></div>');
$('.contact .eyebrow').text('03 — SEU PRÓXIMO PROJETO');
$('.contact h2').html('VAMOS<br>CONSTRUIR<br><em>A SUA BASE.</em>');
$('.contact>div>p:not(.eyebrow)').text('Diga qual é o desafio. Encontre os racks, gabinetes e acessórios para a sua operação.');
$('footer p').text('METAL É A MATÉRIA. CONEXÃO É O PROPÓSITO.');
$('title').text('Metall Rack — Metal. Estrutura. Conexão.');
fs.writeFileSync('index.html', $.html());
