import fs from 'node:fs';
import * as cheerio from 'cheerio';

const backup = 'original-local.html';
if (!fs.existsSync(backup)) fs.copyFileSync('index.html', backup);
const $ = cheerio.load(fs.readFileSync(backup, 'utf8'));
const products = [];
let category = 'rack';
const names = { rack: 'Racks e Telecom', energia: 'Gabinetes e Energia', acessorios: 'Acessórios', fibra: 'Linha Fibra' };
$('h2, .elementor-menu-anchor').each((_, el) => {
  if (names[$(el).attr('id')]) category = $(el).attr('id');
  if (el.tagName !== 'h2' || $(el).find('a').length) return;
  const title = $(el).text().replace(/\s+/g, ' ').trim();
  let card = $(el).closest('.elementor-column');
  if (!card.find('img').length) card = card.parents('.elementor-column').first();
  if (card.find('h2').length !== 1) return;
  const image = card.find('img').first().attr('src');
  const description = card.find('.elementor-widget-text-editor').text().replace(/\s+/g, ' ').trim();
  if (!image || !description) return;
  if (!products.some(p => p.title === title && p.image === image && p.description === description)) products.push({ title, image, description, category });
});
fs.writeFileSync('src/products.json', JSON.stringify(products, null, 2));
const escape = s => s.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
const hero = products.find(p => p.title === 'Rack Server');
fs.writeFileSync('index.html', `<!doctype html>
<html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Metall Rack | Estrutura para ir além</title><meta name="description" content="Racks, gabinetes, acessórios e soluções para infraestrutura de tecnologia, telecomunicações e energia."><link rel="stylesheet" href="/assets/rubik-0a82a7167b.css"><link rel="stylesheet" href="/src/local.css"></head>
<body><a class="skip" href="#produtos">Ir para produtos</a>
<div class="topline"><div class="container">ESTRUTURA FORTE. CONEXÕES QUE TRANSFORMAM.<span>Tecnologia · Telecom · Energia</span></div></div>
<header><div class="container header-inner"><a class="brand" href="#inicio" aria-label="Metall Rack início"><span class="brand-symbol" aria-hidden="true">▤</span><span>METAL<small>RACK</small></span></a><button class="menu-toggle" aria-label="Abrir menu" aria-expanded="false" aria-controls="navigation">☰</button><nav id="navigation"><a href="#inicio">Início</a><a href="#produtos">Produtos</a><a href="#sobre">A empresa</a><a class="button small" href="#contato">Vamos conversar <span>↗</span></a></nav></div></header>
<main><section class="hero container" id="inicio"><div class="hero-copy"><p class="eyebrow"><span></span> INFRAESTRUTURA QUE CONECTA</p><h1>A estrutura para<br>o seu próximo<br><em>grande projeto.</em></h1><p class="intro">Racks, gabinetes e acessórios que organizam, protegem e acompanham a evolução da sua operação.</p><a class="button" href="#produtos">Explore nossos produtos <span>↗</span></a><div class="hero-note"><span class="note-icon">⌘</span><p>Do padrão 19” às soluções sob medida.<br><strong>O seu projeto começa com a estrutura certa.</strong></p></div></div><div class="hero-visual"><span class="visual-label">ENGENHARIA EM CADA DETALHE</span><span class="vertical-label">METALL RACK / INFRAESTRUTURA</span><img src="${hero.image}" alt="${hero.title}" fetchpriority="high"><div class="visual-caption"><span><small>LINHA DATA CENTER</small><strong>${hero.title}</strong></span><a href="#produtos" aria-label="Conhecer os racks">↗</a></div><span class="visual-index">01 / 04</span></div></section>
<div class="applications"><div class="container"><span>SOLUÇÕES PARA<br><strong>cada conexão.</strong></span><span>01 <b>Data Center</b></span><span>02 <b>Telecomunicações</b></span><span>03 <b>Energia</b></span><span>04 <b>Fibra óptica</b></span></div></div>
<section class="catalog container" id="produtos"><div class="section-heading"><div><p class="eyebrow">NOSSO PORTFÓLIO</p><h2>Seu projeto. A estrutura ideal.</h2></div><p>Conheça as linhas e encontre a solução<br>que faz sentido para a sua operação.</p></div><div class="catalog-tools"><div class="filters" role="group" aria-label="Filtrar por categoria"><button class="active" data-filter="all" aria-pressed="true">Todos os produtos</button>${Object.entries(names).map(([id, name]) => `<button data-filter="${id}" aria-pressed="false">${name}</button>`).join('')}</div><label class="search"><span aria-hidden="true">⌕</span><input type="search" id="search" placeholder="Buscar produto" aria-label="Buscar produto"></label></div><p class="result-count" role="status">${products.length} produtos</p><div class="product-grid">${products.map((p,i) => `<article class="product" data-category="${p.category}" data-search="${escape(p.title + ' ' + p.description)}"><div class="product-image"><span class="product-number">${String(i+1).padStart(2,'0')}</span><img src="${p.image}" alt="${escape(p.title)}" loading="lazy" width="400" height="400"></div><div class="product-body"><p class="product-category">${names[p.category]}</p><h3>${escape(p.title)}</h3><p>${escape(p.description)}</p><a href="#contato" data-product="${escape(p.title)}">Consultar produto <span>↗</span></a></div></article>`).join('')}</div><p class="empty" hidden>Nenhum produto encontrado. Tente outro nome ou categoria.</p></section>
<section class="about" id="sobre"><div class="container about-grid"><div><p class="eyebrow">CONHEÇA A METALL RACK</p><h2>Por trás de cada conexão,<br>uma estrutura de confiança.</h2></div><div><p>Equipamentos e estruturas para os setores de tecnologia, telecomunicações e energia. Nosso foco é oferecer soluções confiáveis, com qualidade e compromisso técnico.</p><p>De racks e gabinetes a PDUs e sistemas de climatização, uma linha pensada para as demandas da sua infraestrutura.</p><a href="#contato">Vamos construir seu próximo projeto <span>↗</span></a></div></div></section>
<section class="contact container" id="contato"><div><p class="eyebrow">VAMOS CONVERSAR</p><h2>Grandes projetos<br>começam com uma<br><em>boa conversa.</em></h2><p>Conte o que você precisa. Encontre a estrutura<br>certa para transformar seu projeto em realidade.</p></div><form><div class="form-row"><label>Seu nome<input name="name" autocomplete="name" required placeholder="Como podemos chamar você?"></label><label>Empresa<input name="company" autocomplete="organization" required placeholder="Nome da empresa"></label></div><div class="form-row"><label>E-mail<input name="email" type="email" autocomplete="email" required placeholder="voce@empresa.com.br"></label><label>Telefone / WhatsApp<input name="phone" type="tel" autocomplete="tel" placeholder="(00) 00000-0000"></label></div><label>Produto de interesse<select name="product" id="interest" required><option value="">Selecione uma solução</option>${[...new Set(products.map(p => p.title))].map(t => `<option>${escape(t)}</option>`).join('')}<option>Projeto personalizado</option></select></label><label>Sobre o seu projeto<textarea name="message" rows="3" placeholder="Conte um pouco sobre o que você precisa"></textarea></label><p class="form-help">Formulário de demonstração. O envio ainda não está disponível.</p><button class="button" type="submit">Revisar solicitação <span>↗</span></button><p id="form-notice" role="status" hidden></p></form></section></main>
<footer><div class="container"><a class="brand" href="#inicio"><span class="brand-symbol" aria-hidden="true">▤</span><span>METAL<small>RACK</small></span></a><p>Estrutura para conectar. Qualidade para ir além.</p><a href="#inicio">Voltar ao topo ↑</a></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Metall Rack</span><span>Racks · Gabinetes · Acessórios · Fibra</span></div></footer><script type="module" src="/src/main.js"></script></body></html>`);
console.log(`Preserved ${products.length} distinct product entries.`);
